
cc_test(
    name = "merge_sort_test",
    deps = ["//src/main:kips_algs_lib"],
    srcs = ["merge_sort_test.cpp"],
    copts = ["-I src/main"],
)

cc_test(
    name = "quick_sort_test",
    deps = ["//src/main:kips_algs_lib"],
    srcs = ["quick_sort_test.cpp"],
    copts = ["-I src/main"],
)

